import {
  BINARY_PROPERTY_HINT,
  buildAddOptionsCollectionProperty,
  buildExtensionDialOptionEntries,
  buildHeadersCollectionProperty,
  buildIdOption,
  buildSipDialOptionEntries,
  DUCKING_FACTOR_HINT,
  PLAY_TONE_CUSTOM_HINT,
  PLAYBACK_FILE_PATH_HINT,
  PLAYBACK_HTTP_URL_HINT,
  REF_HINT,
  RECORD_FILE_PATH_HINT,
  RECORD_HTTP_URL_HINT,
  type UiProperty,
} from "./description-fragments";
import { OPTION_DEFAULTS } from "../../shared/option-defaults";
import {
  buildWebSocketDialProfileOptionCollections,
  buildWebSocketDialProfilePrimaryProperties,
  buildWebSocketDialTransportProfileProperty,
} from "../websocket-profiles";

function buildStopOtherMediaOption(): UiProperty {
  return {
    displayName: "Stop Other Media",
    name: "stopOtherMedia",
    type: "boolean",
    default: false,
    description: "Stop other active media on the same leg before starting this one.",
  };
}

function buildGlobalRecordingPrimaryProperties(show: Record<string, unknown>, includeActive: boolean): UiProperty[] {
  const contentShow = includeActive ? { ...show, active: [true] } : show;
  const properties: UiProperty[] = [];
  if (includeActive) {
    properties.push({
      displayName: "Record the call",
      name: "active",
      type: "boolean",
      default: true,
      description: "When enabled, starts global recording for the active leg. When disabled, the action returns without starting recording.",
      displayOptions: { show },
    });
  }
  properties.push(
    {
      displayName: "File Path",
      name: "recordFilePath",
      type: "string",
      default: "",
      required: true,
      description: RECORD_FILE_PATH_HINT,
      displayOptions: { show: contentShow },
    },
    {
      displayName: "File Format",
      name: "recordFileFormat",
      type: "options",
      default: OPTION_DEFAULTS.recordAudio.fileFormat,
      displayOptions: { show: contentShow },
      options: [{ name: "WAV", value: "wav" }, { name: "MP3", value: "mp3" }, { name: "Opus", value: "opus" }, { name: "OGG", value: "ogg" }],
    },
    {
      displayName: "Split Channels",
      name: "recordSplitChannels",
      type: "boolean",
      default: OPTION_DEFAULTS.autoRecording.splitChannels,
      description: "When enabled, call recording writes inbound audio to channel 1 and outbound PBX audio to channel 2.",
      displayOptions: { show: contentShow },
    },
    {
      displayName: "Wait For Recording Completion",
      name: "waitForRecordingCompletion",
      type: "boolean",
      default: OPTION_DEFAULTS.autoRecording.waitForCompletion,
      displayOptions: { show: contentShow },
    },
  );
  return properties;
}

function buildGlobalRecordingOptionsCollections(
  collectionName: string,
  show: Record<string, unknown>,
  idOption: UiProperty,
  includeActive: boolean,
): UiProperty[] {
  const result: UiProperty[] = [];

  if (includeActive) {
    result.push(buildAddOptionsCollectionProperty(collectionName, { ...show, active: [false] }, [idOption]));
  }

  const baseShow = includeActive ? { ...show, active: [true] } : show;

  result.push(
    buildAddOptionsCollectionProperty(collectionName, { ...baseShow, recordFileFormat: ["wav"] }, [
      idOption,
      { displayName: "WAV Sample Rate", name: "recordWavSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.wavSampleRate },
      { displayName: "WAV Bit Depth", name: "recordWavBitDepth", type: "number", default: OPTION_DEFAULTS.recordAudio.wavBitDepth },
    ]),
  );

  result.push(
    buildAddOptionsCollectionProperty(collectionName, { ...baseShow, recordFileFormat: ["mp3", "opus", "ogg"] }, [
      idOption,
      { displayName: "Compressed Sample Rate", name: "recordCompressedSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedSampleRate },
      { displayName: "Compressed Bitrate", name: "recordCompressedBitrate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedBitrateKbps },
    ]),
  );

  return result;
}

export function buildActionNodeProperties(): UiProperty[] {
  return [
    {
      displayName: "Resource",
      name: "resource",
      type: "options",
      noDataExpression: true,
      default: OPTION_DEFAULTS.action.resource,
      options: [
        { name: "Call", value: "call" },
        { name: "Dial", value: "dial" },
        { name: "Media", value: "media" },
        { name: "Queue", value: "queue" },
        { name: "Global recording", value: "recording" },
        { name: "AI", value: "ai" },
        { name: "Respond", value: "respond" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      required: true,
      default: "",
      displayOptions: { show: { resource: ["call"] } },
      options: [
        { name: "Ringing", value: "call.ringing", action: "Ringing tones" },
        { name: "Answer", value: "call.answer", action: "Answer call" },
        { name: "Hangup", value: "call.hangup", action: "Hang up call" },
        { name: "Bridge", value: "call.bridge", action: "Bridge calls" },
        { name: "Unbridge", value: "call.unbridge", action: "Unbridge call" },
        { name: "Wait Event", value: "call.wait", action: "Wait call event" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      required: true,
      default: "",
      displayOptions: { show: { resource: ["dial"] } },
      options: [
        { name: "Make Call", value: "dial.make", action: "Create dial" },
        { name: "Break", value: "dial.break", action: "Break dial" },
        { name: "Wait Event", value: "dial.wait", action: "Wait dial event" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      required: true,
      default: "",
      displayOptions: { show: { resource: ["media"] } },
      options: [
        { name: "Play Audio", value: "media.playAudio", action: "Play audio" },
        { name: "Play Tone", value: "media.playTone", action: "Play tone" },
        { name: "Record Audio", value: "media.recordAudio", action: "Record audio" },
        { name: "Stop Media", value: "media.stopMedia", action: "Stop media" },
        { name: "Wait Media", value: "media.wait", action: "Wait media" },
        { name: "Send DTMF", value: "media.sendDtmf", action: "Send DTMF" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      required: true,
      default: "",
      displayOptions: { show: { resource: ["queue"] } },
      options: [
        { name: "Put Leg In Queue", value: "queue.putLeg", action: "Put leg in queue" },
        { name: "Set Callback", value: "queue.setCallback", action: "Set queue callback" },
        { name: "Get Queue Stats", value: "queue.getStats", action: "Get queue stats" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      required: true,
      default: "",
      displayOptions: { show: { resource: ["recording"] } },
      options: [
        { name: "Start recording", value: "recording.start", action: "Start recording" },
        { name: "Control recording", value: "recording.control", action: "Control recording" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      required: true,
      default: "",
      displayOptions: { show: { resource: ["ai"] } },
      options: [
        { name: "Attach Voice Agent", value: "ai.attachVoiceAgent", action: "Attach voice agent" },
        { name: "Invoke AI Tool", value: "ai.invokeAiTool", action: "Invoke AI tool" },
      ],
    },
    {
      displayName: "Operation",
      name: "operation",
      type: "options",
      noDataExpression: true,
      required: true,
      default: "",
      displayOptions: { show: { resource: ["respond"] } },
      options: [
        { name: "Respond to recording", value: "respond.toRecord", action: "Respond to recording" },
        { name: "Respond To Auth", value: "respond.toAuth", action: "Respond to auth" },
        { name: "Respond To AI Tool", value: "respond.toAiTool", action: "Respond to AI tool" },
      ],
    },

    {
      displayName: "AI Tool Ref",
      name: "ref",
      type: "string",
      default: "",
      required: true,
      description: REF_HINT,
      displayOptions: { show: { resource: ["ai"], operation: ["ai.invokeAiTool"] } },
    },
    {
      displayName: "Function Description",
      name: "aiToolDescription",
      type: "string",
      default: "",
      required: true,
      description: "Natural-language description of what this function does. This text is shown to the AI model to decide when to call it.",
      displayOptions: { show: { resource: ["ai"], operation: ["ai.invokeAiTool"] } },
    },
    {
      displayName: "Flow Parameters",
      name: "aiFlowParams",
      type: "fixedCollection",
      typeOptions: { multipleValues: true },
      default: {},
      description: "Static or expression-based values from the current workflow context. They are passed to the AI trigger as one object named flowParams.",
      displayOptions: { show: { resource: ["ai"], operation: ["ai.invokeAiTool"] } },
      options: [
        {
          name: "item",
          displayName: "Flow Parameter",
          values: [
            { displayName: "Name", name: "name", type: "string", default: "", required: true },
            { displayName: "Value", name: "value", type: "string", default: "", required: true },
          ],
        },
      ],
    },
    {
      displayName: "Function Parameters",
      name: "aiToolParams",
      type: "fixedCollection",
      typeOptions: { multipleValues: true },
      default: {},
      description: "Arguments the AI model is allowed to fill in when it calls this function. They are passed to the AI trigger as one object named toolParams.",
      displayOptions: { show: { resource: ["ai"], operation: ["ai.invokeAiTool"] } },
      options: [
        {
          name: "item",
          displayName: "Function Parameter",
          values: [
            { displayName: "Name", name: "name", type: "string", default: "", required: true },
            {
              displayName: "Type",
              name: "type",
              type: "options",
              default: OPTION_DEFAULTS.aiTool.parameterType,
              required: true,
              options: [
                { name: "String", value: "string" },
                { name: "Number", value: "number" },
                { name: "Integer", value: "integer" },
                { name: "Boolean", value: "boolean" },
              ],
            },
            { displayName: "Description", name: "description", type: "string", default: "", required: true },
            { displayName: "Required", name: "required", type: "boolean", default: false },
          ],
        },
      ],
    },

    { displayName: "Leg A ID", name: "legAId", type: "string", default: "", required: true, displayOptions: { show: { resource: ["call"], operation: ["call.bridge"] } } },
    { displayName: "Leg B ID", name: "legBId", type: "string", default: "", required: true, displayOptions: { show: { resource: ["call"], operation: ["call.bridge"] } } },
    buildAddOptionsCollectionProperty("aiOptions", { resource: ["ai"], operation: ["ai.attachVoiceAgent"] }, [
      {
        displayName: "AI Leg ID",
        name: "legId",
        type: "string",
        default: "",
        description: "Optional explicit websocket AI leg override. If empty, the action resolves aiLegId first, then legId, from the current item.",
      },
    ]),
    { displayName: "Action", name: "recordingControlAction", type: "options", default: OPTION_DEFAULTS.call.recordingControlAction, displayOptions: { show: { resource: ["recording"], operation: ["recording.control"] } }, options: [{ name: "Pause", value: "pause" }, { name: "Resume", value: "resume" }] },
    {
      displayName: "Overall Timeout (Seconds)",
      name: "timeoutSeconds",
      type: "number",
      default: OPTION_DEFAULTS.call.waitTimeoutSeconds,
      description: "Maximum total wait time before the action takes the Timeout branch.",
      displayOptions: { show: { resource: ["call"], operation: ["call.wait"] } },
    },
    {
      displayName: "DTMF Rules",
      name: "rules",
      type: "fixedCollection",
      typeOptions: { multipleValues: true },
      default: {},
      displayOptions: { show: { resource: ["call"], operation: ["call.wait"] } },
      options: [
        {
          name: "item",
          displayName: "Rule",
          values: [
            { displayName: "Pattern", name: "pattern", type: "string", default: "", required: true },
            { displayName: "Label", name: "label", type: "string", default: "", required: true },
          ],
        },
      ],
    },
    { displayName: "DTMF Fallback", name: "waitDtmfFallbackEnabled", type: "boolean", default: OPTION_DEFAULTS.call.waitDtmfFallbackEnabled, displayOptions: { show: { resource: ["call"], operation: ["call.wait"] } } },
    { displayName: "Multi-Digit DTMF Fallback", name: "waitDtmfMultiDigitFallbackEnabled", type: "boolean", default: false, displayOptions: { show: { resource: ["call"], operation: ["call.wait"], waitDtmfFallbackEnabled: [true] } } },
    {
      displayName: "Terminator Digit",
      name: "dtmfTerminatorDigit",
      type: "string",
      default: OPTION_DEFAULTS.call.dtmfTerminatorDigit,
      description: "Single DTMF digit that ends multi-digit fallback capture. If empty, fallback capture ends only when the interdigit timeout expires.",
      displayOptions: { show: { resource: ["call"], operation: ["call.wait"], waitDtmfFallbackEnabled: [true], waitDtmfMultiDigitFallbackEnabled: [true] } },
    },
    {
      displayName: "Leg IDs",
      name: "legIds",
      type: "fixedCollection",
      typeOptions: { multipleValues: true },
      default: {},
      description: "Optional explicit wait target list. If empty, the node waits for the input legId, then input sipPbx.legId.",
      displayOptions: { show: { resource: ["call"], operation: ["call.wait"] } },
      options: [
        {
          name: "item",
          displayName: "Leg ID",
          values: [{ displayName: "Leg ID", name: "legId", type: "string", default: "", required: true }],
        },
      ],
    },
    buildAddOptionsCollectionProperty("callOptions", { resource: ["call"], operation: ["call.bridge"] }, [
      { displayName: "Emit DTMF Events", name: "emitDtmfEvents", type: "boolean", default: true },
      {
        displayName: "Relay DTMF",
        name: "relayDtmf",
        type: "options",
        default: OPTION_DEFAULTS.call.relayDtmf,
        options: [
          { name: "Disabled", value: "disabled" },
          { name: "Auto", value: "auto" },
          { name: "RFC2833", value: "rfc2833" },
          { name: "SIP INFO", value: "info" },
          { name: "Inband", value: "inband" },
        ],
      },
    ]),
    buildAddOptionsCollectionProperty("callOptions", { resource: ["call"], operation: ["call.wait"] }, [
      { displayName: "Interdigit Timeout (Seconds)", name: "interdigitTimeoutSeconds", type: "number", default: OPTION_DEFAULTS.call.interdigitTimeoutSeconds },
    ]),
    buildAddOptionsCollectionProperty("callOptions", { resource: ["call"], operation: ["call.ringing", "call.answer", "call.hangup", "call.unbridge"] }, [buildIdOption("Leg ID", "legId")]),

    {
      displayName: "Mode",
      name: "callMode",
      type: "options",
      default: "",
      required: true,
      displayOptions: { show: { resource: ["dial"], operation: ["dial.make"] } },
      options: [
        { name: "Trunk", value: "trunk" },
        { name: "Extension", value: "extension" },
        { name: "Direct", value: "direct" },
        { name: "WebSocket", value: "websocket" },
      ],
    },
    { displayName: "Trunk Ref", name: "ref", type: "string", default: "", required: true, displayOptions: { show: { resource: ["dial"], operation: ["dial.make"], callMode: ["trunk"] } } },
    { displayName: "Destinations", name: "destination", type: "string", default: "", required: true, description: "Comma-separated phone numbers or SIP users. Do not include server or auth data here; trunk/direct signaling server and authentication always come from the linked credentials.", displayOptions: { show: { resource: ["dial"], operation: ["dial.make"], callMode: ["trunk"] } } },
    {
      displayName: "SIP Connection",
      name: "sipPbxExternal",
      type: "credentials",
      default: "",
      displayOptions: { show: { resource: ["dial"], operation: ["dial.make"], callMode: ["direct"] } },
    },
    { displayName: "Destinations", name: "destination", type: "string", default: "", required: true, description: "Comma-separated phone numbers or SIP users. Do not include server or auth data here; trunk/direct signaling server and authentication always come from the linked credentials.", displayOptions: { show: { resource: ["dial"], operation: ["dial.make"], callMode: ["direct"] } } },
    { displayName: "Extensions", name: "extensionNumbers", type: "string", default: "", required: true, description: "Comma-separated extension numbers. Calls every matching endpoint across all extensions refs in the current flow.", displayOptions: { show: { resource: ["dial"], operation: ["dial.make"], callMode: ["extension"] } } },
    buildAddOptionsCollectionProperty("dialOptions", { resource: ["dial"], operation: ["dial.make"], callMode: ["trunk", "direct"] }, buildSipDialOptionEntries()),
    buildAddOptionsCollectionProperty("dialOptions", { resource: ["dial"], operation: ["dial.make"], callMode: ["extension"] }, buildExtensionDialOptionEntries()),
    buildWebSocketDialTransportProfileProperty({ resource: ["dial"], operation: ["dial.make"], callMode: ["websocket"] }),
    ...buildWebSocketDialProfilePrimaryProperties({ resource: ["dial"], operation: ["dial.make"], callMode: ["websocket"] }),
    {
      displayName: "WebSocket Start Mode",
      name: "websocketStartMode",
      type: "options",
      default: OPTION_DEFAULTS.dial.websocketStartMode,
      description: "Immediate opens the AI provider session as soon as the websocket leg is ready. Deferred keeps the leg unstarted until Attach Voice Agent initializes memory and tools.",
      displayOptions: { show: { resource: ["dial"], operation: ["dial.make"], callMode: ["websocket"], transportProfile: ["openai_realtime", "gemini_live"] } },
      options: [
        { name: "Immediate", value: "immediate" },
        { name: "Deferred", value: "deferred" },
      ],
    },
    ...buildWebSocketDialProfileOptionCollections({ resource: ["dial"], operation: ["dial.make"], callMode: ["websocket"] }),
    { displayName: "Overall Timeout (Seconds)", name: "dialTimeoutSeconds", type: "number", default: OPTION_DEFAULTS.dial.waitTimeoutSeconds, displayOptions: { show: { resource: ["dial"], operation: ["dial.wait"] } } },
    {
      displayName: "Additional Outputs",
      name: "waitEventOutputs",
      type: "multiOptions",
      default: [...OPTION_DEFAULTS.dial.waitEventOutputs],
      displayOptions: { show: { resource: ["dial"], operation: ["dial.wait"] } },
      options: [
        { name: "Ringing", value: "ringing" },
        { name: "Progress", value: "progress" },
        { name: "Rejected", value: "rejected" },
      ],
    },
    {
      displayName: "Dial IDs",
      name: "dialIds",
      type: "fixedCollection",
      typeOptions: { multipleValues: true },
      default: {},
      description: "Optional explicit wait target list. If empty, the node waits for the input dialId, then input sipPbx.dialId.",
      displayOptions: { show: { resource: ["dial"], operation: ["dial.wait"] } },
      options: [
        {
          name: "item",
          displayName: "Dial ID",
          values: [{ displayName: "Dial ID", name: "dialId", type: "string", default: "", required: true }],
        },
      ],
    },
    buildAddOptionsCollectionProperty("dialOptions", { resource: ["dial"], operation: ["dial.break"] }, [
      buildIdOption("Dial ID", "dialId"),
      { displayName: "Reason", name: "dialBreakReason", type: "string", default: OPTION_DEFAULTS.dial.breakReason },
    ]),
    {
      displayName: "Source Type",
      name: "sourceType",
      type: "options",
      default: OPTION_DEFAULTS.playAudio.sourceType,
      required: true,
      displayOptions: { show: { resource: ["media"], operation: ["media.playAudio"] } },
      options: [
        { name: "Binary", value: "binary" },
        { name: "File", value: "file" },
        { name: "HTTP", value: "http" },
      ],
    },
    { displayName: "Binary Property", name: "binaryProperty", type: "string", default: OPTION_DEFAULTS.playAudio.binaryProperty, description: BINARY_PROPERTY_HINT, displayOptions: { show: { resource: ["media"], operation: ["media.playAudio"], sourceType: ["binary"] } } },
    { displayName: "File Path", name: "filePath", type: "string", default: "", required: true, description: PLAYBACK_FILE_PATH_HINT, displayOptions: { show: { resource: ["media"], operation: ["media.playAudio"], sourceType: ["file"] } } },
    { displayName: "URL", name: "playbackHttpUrl", type: "string", default: "", required: true, description: PLAYBACK_HTTP_URL_HINT, displayOptions: { show: { resource: ["media"], operation: ["media.playAudio"], sourceType: ["http"] } } },
    {
      displayName: "HTTP Auth",
      name: "playbackHttpAuthentication",
      type: "options",
      default: OPTION_DEFAULTS.playAudio.httpAuthentication,
      displayOptions: { show: { resource: ["media"], operation: ["media.playAudio"], sourceType: ["http"] } },
      options: [
        { name: "None", value: "none" },
        { name: "Predefined", value: "predefinedCredentialType" },
        { name: "Generic", value: "genericCredentialType" },
      ],
    },
    {
      displayName: "Credential Type",
      name: "playbackHttpNodeCredentialType",
      type: "credentialsSelect",
      credentialTypes: ["extends:oAuth2Api", "extends:oAuth1Api", "has:authenticate"],
      default: null,
      required: true,
      displayOptions: { show: { resource: ["media"], operation: ["media.playAudio"], sourceType: ["http"], playbackHttpAuthentication: ["predefinedCredentialType"] } },
    },
    {
      displayName: "Generic Auth Type",
      name: "playbackHttpGenericAuthType",
      type: "credentialsSelect",
      credentialTypes: ["has:genericAuth"],
      default: null,
      required: true,
      displayOptions: { show: { resource: ["media"], operation: ["media.playAudio"], sourceType: ["http"], playbackHttpAuthentication: ["genericCredentialType"] } },
    },
    { displayName: "Tone", name: "tone", type: "options", default: "", required: true, description: "Built-in tone preset or custom pattern.", displayOptions: { show: { resource: ["media"], operation: ["media.playTone"] } }, options: [...OPTION_DEFAULTS.playTone.presets.map((preset) => ({ name: preset.displayName, value: preset.value, description: preset.description })), { name: "Custom", value: "custom", description: "Provide a custom tone pattern manually." }] },
    { displayName: "Custom Tone", name: "customTone", type: "string", default: "", required: true, description: PLAY_TONE_CUSTOM_HINT, displayOptions: { show: { resource: ["media"], operation: ["media.playTone"], tone: ["custom"] } } },
    { displayName: "Repeat Forever", name: "repeatInfinite", type: "boolean", default: false, displayOptions: { show: { resource: ["media"], operation: ["media.playTone"] } } },
    { displayName: "Interrupt On DTMF", name: "interruptOnDtmf", type: "boolean", default: false, displayOptions: { show: { resource: ["media"], operation: ["media.playAudio", "media.playTone", "media.recordAudio"] } } },
    { displayName: "Interrupt On Voice", name: "interruptOnVoice", type: "boolean", default: false, displayOptions: { show: { resource: ["media"], operation: ["media.playAudio", "media.playTone"] } } },
    { displayName: "Interrupt On Silence", name: "interruptOnSilence", type: "boolean", default: false, displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"] } } },
    { displayName: "Max Duration (Seconds)", name: "maxDurationSeconds", type: "number", default: OPTION_DEFAULTS.recordAudio.maxDurationSeconds, displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"] } } },
    { displayName: "File Format", name: "recordFileFormat", type: "options", default: OPTION_DEFAULTS.recordAudio.fileFormat, displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"] } }, options: [{ name: "WAV", value: "wav" }, { name: "MP3", value: "mp3" }, { name: "Opus", value: "opus" }, { name: "OGG", value: "ogg" }] },
    { displayName: "Output Type", name: "recordOutputType", type: "options", default: OPTION_DEFAULTS.recordAudio.outputType, required: true, displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"] } }, options: [{ name: "Binary", value: "binary" }, { name: "File", value: "file" }, { name: "HTTP", value: "http" }] },
    { displayName: "Binary Property", name: "recordBinaryProperty", type: "string", default: OPTION_DEFAULTS.recordAudio.binaryProperty, description: BINARY_PROPERTY_HINT, displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["binary"] } } },
    { displayName: "File Path", name: "recordFilePath", type: "string", default: "", required: true, description: RECORD_FILE_PATH_HINT, displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["file"] } } },
    { displayName: "URL", name: "recordHttpUrl", type: "string", default: "", required: true, description: RECORD_HTTP_URL_HINT, displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["http"] } } },
    {
      displayName: "HTTP Auth",
      name: "recordHttpAuthentication",
      type: "options",
      default: OPTION_DEFAULTS.recordAudio.httpAuthentication,
      displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["http"] } },
      options: [
        { name: "None", value: "none" },
        { name: "Predefined", value: "predefinedCredentialType" },
        { name: "Generic", value: "genericCredentialType" },
      ],
    },
    {
      displayName: "Credential Type",
      name: "recordHttpNodeCredentialType",
      type: "credentialsSelect",
      credentialTypes: ["extends:oAuth2Api", "extends:oAuth1Api", "has:authenticate"],
      default: null,
      required: true,
      displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["http"], recordHttpAuthentication: ["predefinedCredentialType"] } },
    },
    {
      displayName: "Generic Auth Type",
      name: "recordHttpGenericAuthType",
      type: "credentialsSelect",
      credentialTypes: ["has:genericAuth"],
      default: null,
      required: true,
      displayOptions: { show: { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["http"], recordHttpAuthentication: ["genericCredentialType"] } },
    },
    ...buildGlobalRecordingPrimaryProperties({ resource: ["recording"], operation: ["recording.start"] }, false),
    ...buildGlobalRecordingPrimaryProperties({ resource: ["respond"], operation: ["respond.toRecord"] }, true),
    {
      displayName: "Action",
      name: "authAction",
      type: "options",
      default: OPTION_DEFAULTS.extensionsAction.authAction,
      required: true,
      displayOptions: { show: { resource: ["respond"], operation: ["respond.toAuth"] } },
      options: [
        { name: "Allow", value: "allow" },
        { name: "Verify Digest Password", value: "verify_password" },
        { name: "Not Applicable", value: "not_applicable" },
        { name: "Challenge", value: "challenge" },
        { name: "Deny", value: "deny" },
      ],
    },
    { displayName: "Password", name: "password", type: "string", typeOptions: { password: true }, default: "", required: true, displayOptions: { show: { resource: ["respond"], operation: ["respond.toAuth"], authAction: ["verify_password"] } } },
    {
      displayName: "Extension",
      name: "extension",
      type: "string",
      default: "",
      required: false,
      description: "Used for extension auth only. Leave empty for trunk dynamic address auth, or when the extension can be derived from the auth username.",
      displayOptions: { show: { resource: ["respond"], operation: ["respond.toAuth"], authAction: ["verify_password", "allow"] } },
    },
    { displayName: "Status Code", name: "statusCode", type: "number", default: OPTION_DEFAULTS.extensionsAction.statusCode, required: true, displayOptions: { show: { resource: ["respond"], operation: ["respond.toAuth"], authAction: ["challenge", "deny"] } } },
    { displayName: "Reason", name: "reason", type: "string", default: "", required: true, displayOptions: { show: { resource: ["respond"], operation: ["respond.toAuth"], authAction: ["deny"] } } },
    {
      displayName: "Response Text",
      name: "outputText",
      type: "string",
      default: "",
      required: true,
      description: "Text returned to the AI model as the function result.",
      displayOptions: { show: { resource: ["respond"], operation: ["respond.toAiTool"] } },
    },
    buildAddOptionsCollectionProperty("respondOptions", { resource: ["respond"], operation: ["respond.toAuth", "respond.toAiTool"] }, [buildIdOption("Request ID", "requestId")]),
    { displayName: "Target", name: "stopMediaTarget", type: "options", default: OPTION_DEFAULTS.stopMedia.target, required: true, displayOptions: { show: { resource: ["media"], operation: ["media.stopMedia"] } }, options: [{ name: "Media ID", value: "mediaId" }, { name: "Leg ID", value: "legId" }] },
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.stopMedia"], stopMediaTarget: ["mediaId"] }, [
      buildIdOption("Media ID", "mediaId"),
      { displayName: "Reason", name: "stopMediaReason", type: "string", default: OPTION_DEFAULTS.stopMedia.reason },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.stopMedia"], stopMediaTarget: ["legId"] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "Reason", name: "stopMediaReason", type: "string", default: OPTION_DEFAULTS.stopMedia.reason },
    ]),
    { displayName: "Timeout (Seconds)", name: "waitMediaTimeoutSeconds", type: "number", default: OPTION_DEFAULTS.waitMedia.timeoutSeconds, displayOptions: { show: { resource: ["media"], operation: ["media.wait"] } } },
    {
      displayName: "Media IDs",
      name: "waitMediaIds",
      type: "fixedCollection",
      typeOptions: { multipleValues: true },
      default: {},
      description: "Optional explicit wait target list. If empty, the node waits for the input mediaId, then input sipPbx.mediaId.",
      displayOptions: { show: { resource: ["media"], operation: ["media.wait"] } },
      options: [
        {
          name: "item",
          displayName: "Media ID",
          values: [{ displayName: "Media ID", name: "mediaId", type: "string", default: "", required: true }],
        },
      ],
    },
    { displayName: "Digits", name: "dtmfDigits", type: "string", default: "", required: true, displayOptions: { show: { resource: ["media"], operation: ["media.sendDtmf"] } } },
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.playTone"], interruptOnVoice: [false] }, [
      buildIdOption("Leg ID", "legId"),
      buildStopOtherMediaOption(),
      { displayName: "Ducking Factor", name: "duckingFactor", type: "number", default: OPTION_DEFAULTS.playAudio.duckingFactor, description: DUCKING_FACTOR_HINT },
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.playAudio"], sourceType: ["binary", "file"], interruptOnVoice: [false] }, [
      buildIdOption("Leg ID", "legId"),
      buildStopOtherMediaOption(),
      { displayName: "Ducking Factor", name: "duckingFactor", type: "number", default: OPTION_DEFAULTS.playAudio.duckingFactor, description: DUCKING_FACTOR_HINT },
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.playAudio"], sourceType: ["http"], interruptOnVoice: [false] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "HTTP Method", name: "playbackHttpMethod", type: "options", default: OPTION_DEFAULTS.playAudio.httpMethod, options: [{ name: "GET", value: "GET" }, { name: "POST", value: "POST" }, { name: "PUT", value: "PUT" }] },
      buildHeadersCollectionProperty("HTTP Headers", "playbackHttpHeaders", {}),
      buildStopOtherMediaOption(),
      { displayName: "Ducking Factor", name: "duckingFactor", type: "number", default: OPTION_DEFAULTS.playAudio.duckingFactor, description: DUCKING_FACTOR_HINT },
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.playTone"], interruptOnVoice: [true] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "Voice Threshold", name: "voiceThreshold", type: "number", default: OPTION_DEFAULTS.playAudio.voiceThreshold },
      { displayName: "Voice Duration (ms)", name: "voiceDurationMs", type: "number", default: OPTION_DEFAULTS.playAudio.voiceDurationMs },
      buildStopOtherMediaOption(),
      { displayName: "Ducking Factor", name: "duckingFactor", type: "number", default: OPTION_DEFAULTS.playAudio.duckingFactor, description: DUCKING_FACTOR_HINT },
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.playAudio"], sourceType: ["binary", "file"], interruptOnVoice: [true] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "Voice Threshold", name: "voiceThreshold", type: "number", default: OPTION_DEFAULTS.playAudio.voiceThreshold },
      { displayName: "Voice Duration (ms)", name: "voiceDurationMs", type: "number", default: OPTION_DEFAULTS.playAudio.voiceDurationMs },
      buildStopOtherMediaOption(),
      { displayName: "Ducking Factor", name: "duckingFactor", type: "number", default: OPTION_DEFAULTS.playAudio.duckingFactor, description: DUCKING_FACTOR_HINT },
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.playAudio"], sourceType: ["http"], interruptOnVoice: [true] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "HTTP Method", name: "playbackHttpMethod", type: "options", default: OPTION_DEFAULTS.playAudio.httpMethod, options: [{ name: "GET", value: "GET" }, { name: "POST", value: "POST" }, { name: "PUT", value: "PUT" }] },
      buildHeadersCollectionProperty("HTTP Headers", "playbackHttpHeaders", {}),
      { displayName: "Voice Threshold", name: "voiceThreshold", type: "number", default: OPTION_DEFAULTS.playAudio.voiceThreshold },
      { displayName: "Voice Duration (ms)", name: "voiceDurationMs", type: "number", default: OPTION_DEFAULTS.playAudio.voiceDurationMs },
      buildStopOtherMediaOption(),
      { displayName: "Ducking Factor", name: "duckingFactor", type: "number", default: OPTION_DEFAULTS.playAudio.duckingFactor, description: DUCKING_FACTOR_HINT },
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["binary", "file"], interruptOnSilence: [false], recordFileFormat: ["wav"] }, [
      buildIdOption("Leg ID", "legId"),
      buildStopOtherMediaOption(),
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
      { displayName: "WAV Sample Rate", name: "recordWavSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.wavSampleRate },
      { displayName: "WAV Bit Depth", name: "recordWavBitDepth", type: "number", default: OPTION_DEFAULTS.recordAudio.wavBitDepth },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["http"], interruptOnSilence: [false], recordFileFormat: ["wav"] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "HTTP Method", name: "recordHttpMethod", type: "options", default: OPTION_DEFAULTS.recordAudio.httpMethod, options: [{ name: "POST", value: "POST" }, { name: "PUT", value: "PUT" }] },
      buildHeadersCollectionProperty("HTTP Headers", "recordHttpHeaders", {}),
      buildStopOtherMediaOption(),
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
      { displayName: "WAV Sample Rate", name: "recordWavSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.wavSampleRate },
      { displayName: "WAV Bit Depth", name: "recordWavBitDepth", type: "number", default: OPTION_DEFAULTS.recordAudio.wavBitDepth },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["binary", "file"], interruptOnSilence: [true], recordFileFormat: ["wav"] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "Silence Threshold", name: "silenceThreshold", type: "number", default: OPTION_DEFAULTS.recordAudio.silenceThreshold },
      { displayName: "Silence Duration (ms)", name: "silenceDurationMs", type: "number", default: OPTION_DEFAULTS.recordAudio.silenceDurationMs },
      buildStopOtherMediaOption(),
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
      { displayName: "WAV Sample Rate", name: "recordWavSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.wavSampleRate },
      { displayName: "WAV Bit Depth", name: "recordWavBitDepth", type: "number", default: OPTION_DEFAULTS.recordAudio.wavBitDepth },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["http"], interruptOnSilence: [true], recordFileFormat: ["wav"] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "HTTP Method", name: "recordHttpMethod", type: "options", default: OPTION_DEFAULTS.recordAudio.httpMethod, options: [{ name: "POST", value: "POST" }, { name: "PUT", value: "PUT" }] },
      buildHeadersCollectionProperty("HTTP Headers", "recordHttpHeaders", {}),
      { displayName: "Silence Threshold", name: "silenceThreshold", type: "number", default: OPTION_DEFAULTS.recordAudio.silenceThreshold },
      { displayName: "Silence Duration (ms)", name: "silenceDurationMs", type: "number", default: OPTION_DEFAULTS.recordAudio.silenceDurationMs },
      buildStopOtherMediaOption(),
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
      { displayName: "WAV Sample Rate", name: "recordWavSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.wavSampleRate },
      { displayName: "WAV Bit Depth", name: "recordWavBitDepth", type: "number", default: OPTION_DEFAULTS.recordAudio.wavBitDepth },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["binary", "file"], interruptOnSilence: [false], recordFileFormat: ["mp3", "opus", "ogg"] }, [
      buildIdOption("Leg ID", "legId"),
      buildStopOtherMediaOption(),
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
      { displayName: "Compressed Sample Rate", name: "recordCompressedSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedSampleRate },
      { displayName: "Compressed Bitrate", name: "recordCompressedBitrate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedBitrateKbps },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["http"], interruptOnSilence: [false], recordFileFormat: ["mp3", "opus", "ogg"] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "HTTP Method", name: "recordHttpMethod", type: "options", default: OPTION_DEFAULTS.recordAudio.httpMethod, options: [{ name: "POST", value: "POST" }, { name: "PUT", value: "PUT" }] },
      buildHeadersCollectionProperty("HTTP Headers", "recordHttpHeaders", {}),
      buildStopOtherMediaOption(),
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
      { displayName: "Compressed Sample Rate", name: "recordCompressedSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedSampleRate },
      { displayName: "Compressed Bitrate", name: "recordCompressedBitrate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedBitrateKbps },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["binary", "file"], interruptOnSilence: [true], recordFileFormat: ["mp3", "opus", "ogg"] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "Silence Threshold", name: "silenceThreshold", type: "number", default: OPTION_DEFAULTS.recordAudio.silenceThreshold },
      { displayName: "Silence Duration (ms)", name: "silenceDurationMs", type: "number", default: OPTION_DEFAULTS.recordAudio.silenceDurationMs },
      buildStopOtherMediaOption(),
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
      { displayName: "Compressed Sample Rate", name: "recordCompressedSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedSampleRate },
      { displayName: "Compressed Bitrate", name: "recordCompressedBitrate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedBitrateKbps },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.recordAudio"], recordOutputType: ["http"], interruptOnSilence: [true], recordFileFormat: ["mp3", "opus", "ogg"] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "HTTP Method", name: "recordHttpMethod", type: "options", default: OPTION_DEFAULTS.recordAudio.httpMethod, options: [{ name: "POST", value: "POST" }, { name: "PUT", value: "PUT" }] },
      buildHeadersCollectionProperty("HTTP Headers", "recordHttpHeaders", {}),
      { displayName: "Silence Threshold", name: "silenceThreshold", type: "number", default: OPTION_DEFAULTS.recordAudio.silenceThreshold },
      { displayName: "Silence Duration (ms)", name: "silenceDurationMs", type: "number", default: OPTION_DEFAULTS.recordAudio.silenceDurationMs },
      buildStopOtherMediaOption(),
      { displayName: "Execution Mode", name: "mediaExecutionMode", type: "options", default: OPTION_DEFAULTS.mediaExecution.mode, options: [{ name: "Blocking", value: "blocking" }, { name: "Background", value: "background" }] },
      { displayName: "Compressed Sample Rate", name: "recordCompressedSampleRate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedSampleRate },
      { displayName: "Compressed Bitrate", name: "recordCompressedBitrate", type: "number", default: OPTION_DEFAULTS.recordAudio.compressedBitrateKbps },
    ]),
    buildAddOptionsCollectionProperty("mediaOptions", { resource: ["media"], operation: ["media.sendDtmf"] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "Method", name: "dtmfMethod", type: "options", default: OPTION_DEFAULTS.sendDtmf.method, options: [{ name: "Auto", value: "auto" }, { name: "RFC2833", value: "rfc2833" }, { name: "SIP INFO", value: "info" }, { name: "Inband", value: "inband" }] },
      { displayName: "Duration (ms)", name: "dtmfDurationMs", type: "number", default: OPTION_DEFAULTS.sendDtmf.durationMs },
      { displayName: "Gap (ms)", name: "dtmfGapMs", type: "number", default: OPTION_DEFAULTS.sendDtmf.gapMs },
    ]),
    { displayName: "Target", name: "queueStatsTarget", type: "options", default: OPTION_DEFAULTS.queueAction.statsTarget, required: true, displayOptions: { show: { resource: ["queue"], operation: ["queue.getStats"] } }, options: [{ name: "Queue Ref", value: "ref" }, { name: "Leg ID", value: "legId" }] },
    { displayName: "Queue Ref", name: "ref", type: "string", default: "", required: true, displayOptions: { show: { resource: ["queue"], operation: ["queue.putLeg", "queue.getStats"] }, hide: { queueStatsTarget: ["legId"] } } },
    buildAddOptionsCollectionProperty("queueOptions", { resource: ["queue"], operation: ["queue.putLeg"] }, [
      buildIdOption("Leg ID", "legId"),
      { displayName: "Placement", name: "queuePlacement", type: "options", default: OPTION_DEFAULTS.queueAction.placement, options: [{ name: "Back", value: "back" }, { name: "Front", value: "front" }] },
      {
        displayName: "Rejoin Existing",
        name: "rejoinExisting",
        type: "boolean",
        default: true,
        description: "If a queue entry already exists for the same trunk and caller number and its original leg is gone, reuse it with the new leg instead of adding a separate entry. Typical use: caller hangs up while waiting, callback keeps the entry, caller calls back and lands on the same one.",
      },
      {
        displayName: "Retry Attempts",
        name: "retryAttempts",
        type: "number",
        default: OPTION_DEFAULTS.trigger.queue.retryAttempts,
        description: "Maximum number of retries after a failed dispatch before the entry goes to Offline branch.",
      },
      {
        displayName: "Retry Cooldown (Seconds)",
        name: "retryPauseSeconds",
        type: "number",
        default: OPTION_DEFAULTS.trigger.queue.retryPauseSeconds,
        description: "Delay between a failed dispatch and the next attempt.",
      },
      ...buildSipDialOptionEntries(),
    ]),
    {
      displayName: "Callback Enabled",
      name: "callbackEnabled",
      type: "boolean",
      default: true,
      description: "If enabled, when the caller hangs up the entry switches to callback mode and the next Dispatch arrives with mode=callback. If disabled, hanging up removes the entry from the queue.",
      displayOptions: { show: { resource: ["queue"], operation: ["queue.setCallback"] } },
    },
    buildAddOptionsCollectionProperty("queueOptions", { resource: ["queue"], operation: ["queue.setCallback"] }, [buildIdOption("Leg ID", "legId")]),
    buildAddOptionsCollectionProperty("queueOptions", { resource: ["queue"], operation: ["queue.getStats"], queueStatsTarget: ["legId"] }, [buildIdOption("Leg ID", "legId")]),
    buildAddOptionsCollectionProperty("recordingOptions", { resource: ["recording"], operation: ["recording.control"] }, [buildIdOption("Leg ID", "legId")]),
    ...buildGlobalRecordingOptionsCollections("recordingOptions", { resource: ["recording"], operation: ["recording.start"] }, buildIdOption("Leg ID", "legId"), false),
    ...buildGlobalRecordingOptionsCollections("respondOptions", { resource: ["respond"], operation: ["respond.toRecord"] }, buildIdOption("Request ID", "requestId"), true),
  ];
}
