export const INTERRUPT_REASON_CALL_DTMF = "call_dtmf" as const;
export const INTERRUPT_REASON_CALL_ENDED = "call_ended" as const;
export const INTERRUPT_REASON_CALL_BRIDGE_JOINED = "call_bridge_joined" as const;
export const INTERRUPT_REASON_CALL_BRIDGE_REMOVED_PEER_ENDED = "call_bridge_removed_peer_ended" as const;
export const INTERRUPT_REASON_CALL_BRIDGE_REMOVED_UNBRIDGE = "call_bridge_removed_unbridge" as const;
export const INTERRUPT_REASON_CALL_BRIDGE_REMOVED_ROLLBACK = "call_bridge_removed_rollback" as const;
export const INTERRUPT_REASON_CALL_BRIDGE_REMOVED_REBRIDGE = "call_bridge_removed_rebridge" as const;
export const INTERRUPT_REASON_CALL_QUEUE_PLACED = "call_queue_placed" as const;
export const INTERRUPT_REASON_CALL_QUEUE_REMOVED = "call_queue_removed" as const;
export const INTERRUPT_REASON_MEDIA_VOICE = "media_voice" as const;
export const INTERRUPT_REASON_MEDIA_SILENCE = "media_silence" as const;
export const INTERRUPT_REASON_MEDIA_REPLACED = "media_replaced" as const;
export const INTERRUPT_REASON_MEDIA_STOPPED = "media_stopped" as const;
export const INTERRUPT_REASON_RECORDING_RESTART = "recording_restart" as const;
export const INTERRUPT_REASON_REQUEST_CANCELLED = "request_cancelled" as const;
export const INTERRUPT_REASON_DAEMON_SHUTDOWN = "daemon_shutdown" as const;

export const BUILT_IN_INTERRUPT_REASONS = [
  INTERRUPT_REASON_CALL_DTMF,
  INTERRUPT_REASON_CALL_ENDED,
  INTERRUPT_REASON_CALL_BRIDGE_JOINED,
  INTERRUPT_REASON_CALL_BRIDGE_REMOVED_PEER_ENDED,
  INTERRUPT_REASON_CALL_BRIDGE_REMOVED_UNBRIDGE,
  INTERRUPT_REASON_CALL_BRIDGE_REMOVED_ROLLBACK,
  INTERRUPT_REASON_CALL_BRIDGE_REMOVED_REBRIDGE,
  INTERRUPT_REASON_CALL_QUEUE_PLACED,
  INTERRUPT_REASON_CALL_QUEUE_REMOVED,
  INTERRUPT_REASON_MEDIA_VOICE,
  INTERRUPT_REASON_MEDIA_SILENCE,
  INTERRUPT_REASON_MEDIA_REPLACED,
  INTERRUPT_REASON_MEDIA_STOPPED,
  INTERRUPT_REASON_RECORDING_RESTART,
  INTERRUPT_REASON_REQUEST_CANCELLED,
  INTERRUPT_REASON_DAEMON_SHUTDOWN,
] as const;

export type BuiltInInterruptReason = (typeof BUILT_IN_INTERRUPT_REASONS)[number];

export const CALL_INTERRUPT_REASONS = [
  INTERRUPT_REASON_CALL_BRIDGE_JOINED,
  INTERRUPT_REASON_CALL_BRIDGE_REMOVED_PEER_ENDED,
  INTERRUPT_REASON_CALL_BRIDGE_REMOVED_UNBRIDGE,
  INTERRUPT_REASON_CALL_BRIDGE_REMOVED_ROLLBACK,
  INTERRUPT_REASON_CALL_BRIDGE_REMOVED_REBRIDGE,
  INTERRUPT_REASON_CALL_QUEUE_PLACED,
  INTERRUPT_REASON_CALL_QUEUE_REMOVED,
] as const;

export type CallInterruptReason = (typeof CALL_INTERRUPT_REASONS)[number];

export const DIAL_INTERRUPT_REASONS = [
  INTERRUPT_REASON_CALL_DTMF,
  INTERRUPT_REASON_CALL_ENDED,
] as const;

export type DialInterruptReason = (typeof DIAL_INTERRUPT_REASONS)[number];

export const MEDIA_BUILT_IN_INTERRUPT_REASONS = [
  INTERRUPT_REASON_CALL_DTMF,
  INTERRUPT_REASON_CALL_ENDED,
  INTERRUPT_REASON_CALL_BRIDGE_JOINED,
  INTERRUPT_REASON_MEDIA_VOICE,
  INTERRUPT_REASON_MEDIA_SILENCE,
  INTERRUPT_REASON_MEDIA_REPLACED,
  INTERRUPT_REASON_MEDIA_STOPPED,
  INTERRUPT_REASON_RECORDING_RESTART,
  INTERRUPT_REASON_REQUEST_CANCELLED,
  INTERRUPT_REASON_DAEMON_SHUTDOWN,
] as const;

export type MediaBuiltInInterruptReason = (typeof MEDIA_BUILT_IN_INTERRUPT_REASONS)[number];
