#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

read_arg() {
  local name="$1"
  local fallback="${2:-}"
  local prefix="--${name}="
  for arg in "$@"; do
    if [[ "$arg" == "$prefix"* ]]; then
      printf '%s' "${arg#"$prefix"}"
      return 0
    fi
  done
  printf '%s' "$fallback"
}

PLATFORM="$(read_arg platform "${OSTYPE:-unknown}" "$@")"
ARCH="$(read_arg arch "$(uname -m)" "$@")"
LIBC="$(read_arg libc "" "$@")"
BUILD_ROOT="$(read_arg build-root "${REPO_ROOT}/build-ffaudio/${PLATFORM}-${ARCH}${LIBC:+-${LIBC}}" "$@")"
JOBS="$(read_arg jobs "" "$@")"
REUSE_EXISTING="$(read_arg reuse-existing false "$@")"

if [[ "${PLATFORM}" != "linux" ]]; then
  echo "[ffaudio] unsupported vendor build platform ${PLATFORM}; published native prebuilds are Linux-only" >&2
  exit 1
fi

if [[ "${LIBC}" != "glibc" && "${LIBC}" != "musl" ]]; then
  echo "[ffaudio] unsupported Linux libc ${LIBC}; expected glibc or musl" >&2
  exit 1
fi

if [[ -z "$JOBS" ]]; then
  if command -v nproc >/dev/null 2>&1; then
    JOBS="$(nproc)"
  else
    JOBS="$(sysctl -n hw.ncpu 2>/dev/null || printf '4')"
  fi
fi

PREFIX_DIR="${BUILD_ROOT}/prefix"
OPUS_BUILD_DIR="${BUILD_ROOT}/opus-build"
LAME_BUILD_DIR="${BUILD_ROOT}/lame-build"
FFMPEG_BUILD_DIR="${BUILD_ROOT}/ffmpeg-build"
FFMPEG_INSTALL_DIR="${BUILD_ROOT}/ffmpeg-install"
FFMPEG_SOURCE_DIR="${BUILD_ROOT}/ffmpeg-source"
PROFILE_JSON="${BUILD_ROOT}/ffaudio-profile.json"
PKG_CONFIG_DIR="${PREFIX_DIR}/lib/pkgconfig"
PKG_CONFIG_SHIM="${REPO_ROOT}/scripts/ffaudio-pkg-config.js"
PKG_CONFIG_WRAPPER="${BUILD_ROOT}/ffaudio-pkg-config"

mkdir -p "${BUILD_ROOT}"
node "${REPO_ROOT}/scripts/ffaudio-build-profile.js" --json > "${PROFILE_JSON}"
read -r -a CONFIGURE_FLAGS_ARR <<< "$(node -e "const p=require('${REPO_ROOT}/scripts/ffaudio-build-profile.js'); console.log(p.toConfigureFlags(p.PROFILE).join(' '))")"

echo "[ffaudio] build root: ${BUILD_ROOT}"
echo "[ffaudio] tuple: ${PLATFORM}-${ARCH}${LIBC:+-${LIBC}}"

if [[ "${REUSE_EXISTING}" != "true" ]]; then
  rm -rf "${OPUS_BUILD_DIR}" "${LAME_BUILD_DIR}" "${FFMPEG_BUILD_DIR}" "${FFMPEG_INSTALL_DIR}" "${FFMPEG_SOURCE_DIR}"
fi
mkdir -p "${PREFIX_DIR}" "${OPUS_BUILD_DIR}" "${LAME_BUILD_DIR}" "${FFMPEG_BUILD_DIR}" "${FFMPEG_INSTALL_DIR}" "${FFMPEG_SOURCE_DIR}" "${PKG_CONFIG_DIR}"

cat > "${PKG_CONFIG_WRAPPER}" <<EOF
#!/usr/bin/env bash
FFAUDIO_PKGCONFIG_DIR="${PKG_CONFIG_DIR}" exec node "${PKG_CONFIG_SHIM}" "\$@"
EOF
chmod +x "${PKG_CONFIG_WRAPPER}"

write_pkg_config_file() {
  local file_path="$1"
  local package_name="$2"
  local package_description="$3"
  local package_version="$4"
  local cflags="$5"
  local libs="$6"
  local private_libs="${7:-}"
  {
    cat <<EOF
prefix=${PREFIX_DIR}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: ${package_name}
Description: ${package_description}
Version: ${package_version}
Libs: -L\${libdir} ${libs}
EOF
    if [[ -n "${private_libs}" ]]; then
      printf 'Libs.private: %s\n' "${private_libs}"
    fi
    printf 'Cflags: %s\n' "${cflags}"
  } > "${file_path}"
}

copy_tree_contents() {
  local src_dir="$1"
  local dst_dir="$2"
  mkdir -p "${dst_dir}"
  if [[ -d "${src_dir}" ]]; then
    cp -R "${src_dir}/." "${dst_dir}/"
  fi
}

write_ffmpeg_stub_makefile() {
  local file_path="$1"
  local body="${2:-}"
  mkdir -p "$(dirname "${file_path}")"
  {
    printf '# Auto-generated by scripts/build-ffaudio-vendor.sh for reduced source-build payload.\n'
    printf '%s\n' "${body}"
  } > "${file_path}"
}

prepare_reduced_ffmpeg_source_tree() {
  local source_root="${REPO_ROOT}/vendor/ffmpeg"
  local stage_root="${FFMPEG_SOURCE_DIR}"
  rm -rf "${stage_root}"
  mkdir -p "${stage_root}"

  for file in COPYING.GPLv2 COPYING.GPLv3 COPYING.LGPLv2.1 COPYING.LGPLv3 INSTALL.md LICENSE.md Makefile README.md RELEASE configure; do
    cp "${source_root}/${file}" "${stage_root}/${file}"
  done
  for dir in compat ffbuild libavcodec libavformat libavutil libswresample; do
    copy_tree_contents "${source_root}/${dir}" "${stage_root}/${dir}"
  done

  mkdir -p "${stage_root}/libavdevice" "${stage_root}/libavfilter"
  cp "${source_root}/libavdevice/alldevices.c" "${stage_root}/libavdevice/alldevices.c"
  cp "${source_root}/libavfilter/allfilters.c" "${stage_root}/libavfilter/allfilters.c"

  write_ffmpeg_stub_makefile "${stage_root}/tools/Makefile" $'TOOLS =\nOUTDIRS += tools\nclean::\n\t$(RM) $(CLEANSUFFIXES:%=tools/%)\n-include $(wildcard tools/*.d)'
  write_ffmpeg_stub_makefile "${stage_root}/fftools/Makefile" $'clean::\n\t$(RM) $(CLEANSUFFIXES:%=fftools/%)'
  write_ffmpeg_stub_makefile "${stage_root}/doc/Makefile" $'DOCS =\ndocclean::\n\t@:\n.PHONY: doc documentation apidoc'
  write_ffmpeg_stub_makefile "${stage_root}/doc/examples/Makefile" $'examplesclean::\n\t@:\n.PHONY: examples'
  write_ffmpeg_stub_makefile "${stage_root}/tests/Makefile" $''
}

echo "[ffaudio] building static libopus"
OPUS_CMAKE_ARGS=(
  -S "${REPO_ROOT}/vendor/libopus"
  -B "${OPUS_BUILD_DIR}"
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_POLICY_VERSION_MINIMUM=3.5
  -DCMAKE_INSTALL_PREFIX="${PREFIX_DIR}"
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  -DBUILD_SHARED_LIBS=OFF
  -DOPUS_DISABLE_INTRINSICS=ON
  -DOPUS_BUILD_TESTING=OFF
  -DOPUS_BUILD_PROGRAMS=OFF
)
cmake "${OPUS_CMAKE_ARGS[@]}"
cmake --build "${OPUS_BUILD_DIR}" --parallel "${JOBS}"
cmake --install "${OPUS_BUILD_DIR}"

echo "[ffaudio] building static libmp3lame"
(
  cd "${LAME_BUILD_DIR}"
  CFLAGS="-fPIC" "${REPO_ROOT}/vendor/lame/configure" \
    --prefix="${PREFIX_DIR}" \
    --disable-shared \
    --enable-static \
    --disable-decoder \
    --disable-libmpg123 \
    --disable-gtktest \
    --disable-analyzer-hooks \
    --disable-frontend
  make -C libmp3lame -j"${JOBS}"
)

mkdir -p "${PREFIX_DIR}/lib" "${PREFIX_DIR}/include/lame"
cp "${LAME_BUILD_DIR}/libmp3lame/.libs/libmp3lame.a" "${PREFIX_DIR}/lib/libmp3lame.a"
cp "${REPO_ROOT}/vendor/lame/include/lame.h" "${PREFIX_DIR}/include/lame/lame.h"

LAME_VERSION="$(awk -F"'" '/^PACKAGE_VERSION=/{print $2; exit}' "${REPO_ROOT}/vendor/lame/configure" 2>/dev/null || true)"
if [[ -z "${LAME_VERSION}" ]]; then
  LAME_VERSION="3.100"
fi

write_pkg_config_file "${PKG_CONFIG_DIR}/libmp3lame.pc" "libmp3lame" "LAME MP3 encoder" "${LAME_VERSION}" "-I\${includedir}/lame" "-lmp3lame"
write_pkg_config_file "${PKG_CONFIG_DIR}/lame.pc" "lame" "LAME MP3 encoder" "${LAME_VERSION}" "-I\${includedir}/lame" "-lmp3lame"

echo "[ffaudio] building static ffmpeg audio libs"
prepare_reduced_ffmpeg_source_tree
(
  cd "${FFMPEG_BUILD_DIR}"
  PKG_CONFIG_PATH="${PKG_CONFIG_DIR}" \
  PKG_CONFIG_LIBDIR="${PKG_CONFIG_DIR}" \
  "${FFMPEG_SOURCE_DIR}/configure" \
    --prefix="${FFMPEG_INSTALL_DIR}" \
    --enable-pic \
    --enable-small \
    --disable-asm \
    --pkg-config="${PKG_CONFIG_WRAPPER}" \
    --extra-cflags="-I${PREFIX_DIR}/include -fPIC" \
    --extra-ldflags="-L${PREFIX_DIR}/lib" \
    --extra-libs="-lm" \
    "${CONFIGURE_FLAGS_ARR[@]}"
  make -j"${JOBS}"
  make install-libs install-headers
)

echo "[ffaudio] completed"
echo "{\"ok\":true,\"buildRoot\":\"${BUILD_ROOT}\",\"prefixDir\":\"${PREFIX_DIR}\",\"ffmpegInstallDir\":\"${FFMPEG_INSTALL_DIR}\",\"profileJson\":\"${PROFILE_JSON}\"}"
